[features]
seeds = false
skip-lint = false
[programs.localnet]
gif_portal_solana_backend = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/ricardomnnteiroelima/.config/solana/id.json"

[scripts]
test = "node tests/gif-portal-solana-backend.js"
